"""empty message

Revision ID: 46dd624247ee
Revises: cddfe4846084
Create Date: 2020-02-14 12:37:47.125043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46dd624247ee'
down_revision = 'cddfe4846084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('picture', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'picture')
    # ### end Alembic commands ###
