"""empty message

Revision ID: a63c6b286bba
Revises: 
Create Date: 2020-02-13 17:56:02.612667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63c6b286bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surName', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('userBio', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'author')
    )
    op.create_table('user_skills',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['accounts.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills')
    op.drop_table('tasks')
    op.drop_table('skills')
    op.drop_table('accounts')
    # ### end Alembic commands ###
